server/controllers/dashboardController.test.ts
server/controllers/dashboardController.ts
server/routes/index.test.ts
server/utils/userUtils.test.ts
server/utils/userUtils.ts

Added in some specific mentions of CAS2 Bail so that people are clear about what they are looking at.
Removed the "View your Prisons Applications" tile as we're not sure whether this will be in the MVP yet

Add Bail specific mentions and remove view your prisons tile

---

.husky/pre-commit

This hook is currently adding friction but not much value.
confirm:

Remove pre commit hook

---

server/utils/nunjucksSetup.ts
server/views/partials/layout.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-10?atlOrigin=eyJpIjoiYzhhYmRlYzgzMWYxNGMxZWIwNjU4ZjU5ZDVmYjM0ZDAiLCJwIjoiaiJ9)
Update the views to reconcile with the new asset approach in the typescript
template.

Fix asset paths

---

assets/scss/application.scss
server/views/applications/ineligible.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-27
confirm:

Remove not eligible guidance

---

.github/workflows/e2e_tests.yml
.github/workflows/pipeline.yml

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-55?atlOrigin=eyJpIjoiZmZhZTE4MjI4YmYyNDdlYzkxOTZkZTAxYjFiYzE1NzIiLCJwIjoiaiJ9)
We want to run the e2e test as part of the CI pipeline.
As they are run against the development environment, we only run them
after a change has been merged into main and deployed to development.

Run e2e tests in github actions pipeline

---

e2e-tests/steps/apply.ts
e2e-tests/steps/bailInformationSection.ts
e2e-tests/tests/01_apply_as_pom.spec.ts
server/form-pages/apply/bail-information/bail-conditions-and-support-sessions/index.ts
server/form-pages/apply/bail-information/bail-conditions-and-support-sessions/mandatorySupportSessions.test.ts
server/form-pages/apply/bail-information/bail-conditions-and-support-sessions/mandatorySupportSessions.ts
server/form-pages/apply/bail-information/bail-conditions-and-support-sessions/nonStandardBailConditions.test.ts
server/form-pages/apply/bail-information/bail-conditions-and-support-sessions/nonStandardBailConditions.ts
server/form-pages/apply/bail-information/index.ts
server/form-pages/apply/index.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/bail-conditions-and-support-sessions/mandatory-support-sessions.njk
server/views/applications/pages/bail-conditions-and-support-sessions/non-standard-bail-conditions.njk

Jira tickets:
https://dsdmoj.atlassian.net/browse/CBA-59
https://dsdmoj.atlassian.net/browse/CBA-60
https://dsdmoj.atlassian.net/browse/CBA-51
Adds a new section, bail information, together with a task with two pages. For now, there is no validation on either page. We may revisit this when we understand user needs better.
confirm:

Add new bail information section

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
server/form-pages/apply/risks-and-needs/health-needs/brainInjury.test.ts
server/form-pages/apply/risks-and-needs/health-needs/brainInjury.ts
server/form-pages/apply/risks-and-needs/health-needs/index.ts
server/form-pages/apply/risks-and-needs/health-needs/liaisonAndDiversion.test.ts
server/form-pages/apply/risks-and-needs/health-needs/liaisonAndDiversion.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/health-needs/_health-needs-screen.njk
server/views/applications/pages/health-needs/liaison-and-diversion.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-58?atlOrigin=eyJpIjoiZWE2MzRhZWE3NDYxNGMwNzg4MGI5MzNlNmQ4ZmJkYTciLCJwIjoiaiJ9)
* Add liaison & diversion assessment question to health needs task
confirm:

Add liaison & diversion assessment question to health needs task

---

e2e-tests/steps/aboutThePersonSection.ts
integration_tests/fixtures/applicationDocument.json
server/form-pages/apply/about-the-person/personal-information/workingMobilePhone.test.ts
server/form-pages/apply/about-the-person/personal-information/workingMobilePhone.ts
server/form-pages/utils/questions.ts

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-70
Corrects wording of mobile phone question for bail context
confirm:

CBA-70 - correct wording of mobile phone question for bail context

---

e2e-tests/steps/apply.ts
e2e-tests/steps/bailInformationSection.ts
e2e-tests/tests/01_apply_as_pom.spec.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/bailHearingArranger.test.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/bailHearingArranger.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/bailHearingContact.test.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/bailHearingContact.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/consultLegalAdvisor.test.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/consultLegalAdvisor.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/index.ts
server/form-pages/apply/bail-information/index.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/bail-hearing-arrangement/bail-hearing-arranger.njk
server/views/applications/pages/bail-hearing-arrangement/bail-hearing-contact.njk
server/views/applications/pages/bail-hearing-arrangement/consult-legal-advisor.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-63?atlOrigin=eyJpIjoiYmNkZTgyMjgwMGY5NGUyOThkYWM5MmM1NmRmNjhlZTgiLCJwIjoiaiJ9)
* Add Bail hearing arrangements task and pages
confirm:

Add bail hearing arrangements task

---

server/form-pages/utils/questions.ts

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-58?atlOrigin=eyJpIjoiN2E5ZjY2M2EyZTVjNGRkZjhkOGVmYzc3ZmQzNTk4OWUiLCJwIjoiaiJ9)
confirm:

Update liaison & diversion copy

---

server/views/applications/taskList.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-98.
The prison name is not necessarily relevant in a bail context, so for now we are removing it.
confirm:

Remove prison name from task list page

---

server/form-pages/utils/questions.ts

Our users in the bail context will mostly be Bail Information Officers, so this text needs updating.
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-99.
confirm:

Update job title hint text

---

server/utils/userUtils.ts

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-109
confirm:

Remove start button description text

---

e2e-tests/steps/apply.ts
e2e-tests/steps/beforeYouStartSection.ts
e2e-tests/tests/01_apply_as_pom.spec.ts
integration_tests/fixtures/applicationData.json
server/form-pages/apply/before-you-start/index.ts
server/form-pages/apply/before-you-start/solicitor-details/contactInformation.test.ts
server/form-pages/apply/before-you-start/solicitor-details/contactInformation.ts
server/form-pages/apply/before-you-start/solicitor-details/index.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/solicitor-details/contact-information.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-106?atlOrigin=eyJpIjoiNzc4YTExMGMxZWIyNDhlY2JkMjVkYTQ3ZjE2NWMyYTUiLCJwIjoiaiJ9)
- Add task for solicitor details 
confirm:

Introduce solicitor details task

---

server/form-pages/utils/questions.ts

These questions should have been removed previously. Their presence was causing the check your answers page to error.
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-129
confirm:

Remove RoSH summary questions

---

e2e-tests/steps/apply.ts
e2e-tests/steps/bailInformationSection.ts
e2e-tests/steps/beforeYouStartSection.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/bailHearingContact.test.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/bailHearingContact.ts
server/form-pages/apply/bail-information/bail-hearing-arrangement/index.ts
server/form-pages/apply/before-you-start/solicitor-details/consultSolicitor.test.ts
server/form-pages/apply/before-you-start/solicitor-details/consultSolicitor.ts
server/form-pages/apply/before-you-start/solicitor-details/contactInformation.test.ts
server/form-pages/apply/before-you-start/solicitor-details/contactInformation.ts
server/form-pages/apply/before-you-start/solicitor-details/index.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/solicitor-details/consult-solicitor.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-118
Moves the consult solicitor page to within the solicitor details task.
confirm:

CBA-118 move the page have you spoken to the applicant s legal advisor about this application to the add referrer details task

---

assets/scss/application.scss
assets/scss/components/_copy-text.scss
assets/scss/components/_side-nav.scss
assets/scss/components/_status-box.scss
assets/scss/components/_submitted-application-panel.scss
assets/scss/components/_summary-card.scss
assets/scss/components/_tag.scss
assets/scss/components/_timeline.scss

We missed these styles when copying over the HDC code, but we still need them in our service.
confirm:

CBA-122: Add missing styles

---

e2e-tests/steps/bailInformationSection.ts
server/form-pages/apply/bail-information/bail-hearing-information/bailHearingArranger.test.ts
server/form-pages/apply/bail-information/bail-hearing-information/bailHearingArranger.ts
server/form-pages/apply/bail-information/bail-hearing-information/bailHearingDate.test.ts
server/form-pages/apply/bail-information/bail-hearing-information/bailHearingDate.ts
server/form-pages/apply/bail-information/bail-hearing-information/bailHearingMedium.test.ts
server/form-pages/apply/bail-information/bail-hearing-information/bailHearingMedium.ts
server/form-pages/apply/bail-information/bail-hearing-information/courtName.test.ts
server/form-pages/apply/bail-information/bail-hearing-information/courtName.ts
server/form-pages/apply/bail-information/bail-hearing-information/index.ts

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-128
confirm:

CBA-128: reorder the add bail hearing information task

---

server/views/partials/submittedApplicationDetails.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-126
Not to be merged until applicationOrigin is added to Cas2v2SubmittedApplication model (which should be imminent).
confirm:

CBA-126: Add application type to submitted application details partial

---

cypress.config.ts
integration_tests/mockApis/auth.ts
integration_tests/pages/page.ts
integration_tests/tasks/accessibilityViolations.ts
integration_tests/tsconfig.json
package-lock.json
package.json

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-197?atlOrigin=eyJpIjoiN2JhNjk5N2Q0NDJiNDM2NGJkOTE3MTZmYzhlYjk2MjEiLCJwIjoiaiJ9)
We want to know when an accessibility regression is introduced. This change ensures we run accessibility tests part of our integration test suite. If a regression is introduced, the tests will fail and block merging to main.
confirm:

Add automated accessibility tests

---

assets/scss/pages/_dashboard-index.scss
server/utils/userUtils.ts
server/views/dashboard/index.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-193
Updates landing page tile content and stylings.
confirm:

CBA-193: amend pre dashboard page

---

e2e-tests/pages/apply/dashboardPage.ts

Fix E2E test dashboard tile text

---

server/views/partials/applicationSoftDeleteGuidance.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-232
confirm:

CBA-232: remove HDC related guidance on which applications will not appear on dashboard

---

e2e-tests/steps/apply.ts
integration_tests/pages/apply/submit_application/applicationSubmittedPage.ts
integration_tests/tests/apply/submit_application/complete_confirm_submission_page.cy.ts
server/views/applications/confirm.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-246
Updates content and design of application submitted page.
confirm:

CBA-246: amend application submission confirmation page

---

.github/workflows/deploy_to_env.yml

Adding the test env value so that deployments to the test environment can be made through Github Actions

Add the test env value for deployments

---

.github/workflows/pipeline.yml

Adds a test deployment job as part of the pipeline in github actions

Add test deployment job

---

e2e-tests/steps/reports.ts
e2e-tests/tests/03_assess.spec.ts
e2e-tests/tests/04_reports.spec.ts

Skip failing tests

---

helm_deploy/values-test.yaml

HAAR team has come back with a preferred solution which is replacing values on their end
Removing the overrides to client credentials
Once we've merged it will be auto-deployed to the dev environment. Manual deployment to test will be required in order to test

Remove the client cred override values set in test

---

server/views/applications/pages/risk-information/self-harm.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-260?atlOrigin=eyJpIjoiYWNhYWNjMzUyNmFiNDdkNTgxNzdlNjdiZTI2YzFlNmUiLCJwIjoiaiJ9)
confirm:

Fix missing hint text on self harm page

---

integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/risks-and-needs/risk-information/violenceAndArsonPage.ts
integration_tests/tests/apply/risks-and-needs/risk-information/complete_violence_and_arson_page.cy.ts
server/form-pages/apply/risks-and-needs/risk-information/violenceAndArson.test.ts
server/form-pages/apply/risks-and-needs/risk-information/violenceAndArson.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/risk-information/violence-and-arson.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-262?atlOrigin=eyJpIjoiNjA0MGM4ZDIwMmY2NDY2ZjhhZjVlMzEwMTI4YTgwY2EiLCJwIjoiaiJ9)
* Add questions and validation to the violence and arson page
* Update hint text for self harm page
confirm:

Update violence and arson risk page with content

---

package.json

Reverts ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui#88

Revert "Update dependency eslint-plugin-cypress to v4"

---

e2e-tests/steps/risksAndNeedsSection.ts

Fix violence and arson e2e tests

---

.github/workflows/e2e_tests.yml

Our e2e tests in github actions is reporting the following error
```
Error: Cannot find module '@playwright/test'
```
This PR adds temporary workflow jobs to investigate the error:
* Try to find playwright dependency on CI machine
* Output the total size of node_modules
* Download a copy of the node_modules folder
confirm:

Debug playwright not found error

---

playwright.config.ts

Retain videos of e2e tests on failure

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/risks-and-needs/risk-information/riskManagementArrangementsPage.ts
integration_tests/tests/apply/risks-and-needs/risk-information/complete_risk_management_arrangements_page.cy.ts
server/form-pages/apply/risks-and-needs/risk-information/additionalConcerns.test.ts
server/form-pages/apply/risks-and-needs/risk-information/additionalConcerns.ts
server/form-pages/apply/risks-and-needs/risk-information/index.ts
server/form-pages/apply/risks-and-needs/risk-information/riskManagementArrangements.test.ts
server/form-pages/apply/risks-and-needs/risk-information/riskManagementArrangements.ts
server/form-pages/utils/questions.ts
server/utils/checkYourAnswersUtils.test.ts
server/views/applications/pages/risk-information/_risk-information-screen.njk
server/views/applications/pages/risk-information/risk-management-arrangements.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-369
Adds new risk management arrangements page, which is largely a copy of the same page in HDC.
confirm:

CBA-369: build multi agency risk management arrangements page

---

server/data/restClientMetricsMiddleware.test.ts

This test has always been skipped, and the ‘FIXME’ comment on it was flagged in the HDC IT health check. I don’t think we need it.
confirm:

Remove skipped test

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/risks_and_needs/health-needs/otherHealthPage.ts
integration_tests/tests/apply/risks_and_needs/health-needs/other_health.cy.ts
server/form-pages/apply/risks-and-needs/health-needs/otherHealth.test.ts
server/form-pages/apply/risks-and-needs/health-needs/otherHealth.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/health-needs/_health-needs-screen.njk
server/views/applications/pages/health-needs/other-health.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-284?atlOrigin=eyJpIjoiNWI5MzU5N2UwY2M0NDliNzlhODNiZDkxMjNiNTI5NGUiLCJwIjoiaiJ9)
Updates the other health needs page of the health needs section
confirm:

Update other health needs page

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/pages/apply/risks-and-needs/risk-information/concernsPage.ts
integration_tests/tests/apply/risks-and-needs/risk-information/complete_concerns_page.cy.ts
server/form-pages/apply/risks-and-needs/risk-information/concerns.test.ts
server/form-pages/apply/risks-and-needs/risk-information/concerns.ts
server/views/applications/pages/risk-information/concerns.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-275?atlOrigin=eyJpIjoiNDI2ZDBhNzUwYjBmNDBhYmE1OTU1OWQwMGQ1YjNkMDYiLCJwIjoiaiJ9)
Adds guidance content to the risk information concerns page.
confirm:

Update concerns page

---

assets/scss/application.scss
assets/scss/components/_guidance-panel.scss
e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/pages/apply/risks_and_needs/health-needs/healthNeedsInformationPage.ts
integration_tests/tests/apply/risks_and_needs/health-needs/health_needs_information.cy.ts
server/form-pages/apply/risks-and-needs/health-needs/healthNeedsInformation.test.ts
server/form-pages/apply/risks-and-needs/health-needs/healthNeedsInformation.ts
server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts
server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts
server/views/applications/confirm-submission.njk
server/views/applications/pages/funding-information/funding-cas2-accommodation.njk
server/views/applications/pages/health-needs/health-needs-information.njk
server/views/applications/pages/risk-information/additional-concerns.njk
server/views/applications/pages/risk-information/concerns.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-281
confirm:

CBA-281: change content on provide information about applicants health needs page

---

e2e-tests/tests/04_reports.spec.ts

This was an expected test failure, but the API issue has now been fixed.
confirm:

Remove failing test flag

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/risks_and_needs/health-needs/substanceMisusePage.ts
integration_tests/tests/apply/risks_and_needs/health-needs/substance_misuse.cy.ts
server/@types/ui/index.d.ts
server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts
server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts
server/form-pages/apply/risks-and-needs/risk-information/livingInTheCommunity.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/health-needs/substance-misuse.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-282
Adds new questions to substance and alcohol use page
confirm:

CBA-282 change content on substance and alcohol use details page

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/risks_and_needs/health-needs/physicalHealthPage.ts
integration_tests/tests/apply/risks_and_needs/health-needs/physical_health.cy.ts
server/form-pages/apply/risks-and-needs/health-needs/physicalHealth.test.ts
server/form-pages/apply/risks-and-needs/health-needs/physicalHealth.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/health-needs/physical-health.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-283
confirm:

CBA-283 change content on physical health and mobility page

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/risks_and_needs/health-needs/mentalHealthPage.ts
integration_tests/tests/apply/risks_and_needs/health-needs/mental_health.cy.ts
server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.test.ts
server/form-pages/apply/risks-and-needs/health-needs/mentalHealth.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/health-needs/mental-health.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-286
confirm:

CBA-286 change content on mental health page

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/pages/apply/risks_and_needs/health-needs/communicationAndLanguagePage.ts
server/form-pages/apply/risks-and-needs/health-needs/communicationAndLanguage.test.ts
server/form-pages/apply/risks-and-needs/health-needs/communicationAndLanguage.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/health-needs/communication-and-language.njk

The don’t know field is now superfluous, so we have removed it.
confirm:

Update communication and language page

---

server/views/static/privacy-notice.njk

https://dsdmoj.atlassian.net/browse/CBA-357
Updates privacy policy, https://vivace1.sharepoint.com/:w:/s/EXTERNAL-C646CAS2BailApplications/EdIuqlooXrhHnHztCQl1W0IBoD2RFjIaH1V9A1NbVEH4vA?e=1oAEva
Whole page changes
confirm:

fix: update privacy policy

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/pages/apply/risks_and_needs/health-needs/brainInjuryPage.ts
server/form-pages/apply/risks-and-needs/health-needs/brainInjury.test.ts
server/form-pages/apply/risks-and-needs/health-needs/brainInjury.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/health-needs/brain-injury.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-352
confirm:

CBA-352 remove i dont know options and make content changes to brain injury page and error messages

---

e2e-tests/steps/aboutThePersonSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/about_the_person/personal_information/custodyLocationPage.ts
integration_tests/tests/apply/about_the_person/personal-information/custody_location.cy.ts
server/form-pages/apply/about-the-person/personal-information/custodyLocation.test.ts
server/form-pages/apply/about-the-person/personal-information/custodyLocation.ts
server/form-pages/apply/about-the-person/personal-information/index.ts
server/form-pages/apply/about-the-person/personal-information/workingMobilePhone.test.ts
server/form-pages/apply/about-the-person/personal-information/workingMobilePhone.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/personal-information/custody-location.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-362
confirm:

CBA-362 build where are they being held in custody page

---

server/views/partials/layout.njk

https://dsdmoj.atlassian.net/browse/CBA-353
Removed link to accessibility statement in footer
confirm:

Removed link to accessibility statement

---

e2e-tests/pages/basePage.ts
e2e-tests/steps/beforeYouStartSection.ts
server/form-pages/apply/before-you-start/confirm-consent/confirmConsent.test.ts
server/form-pages/apply/before-you-start/confirm-consent/confirmConsent.ts
server/form-pages/utils/questions.ts
server/views/applications/consent-refused.njk
server/views/applications/pages/confirm-consent/confirm-consent.njk

https://dsdmoj.atlassian.net/browse/CBA-200
Updates to the text on the confirmation page
confirm:

feat: updates cnsent page CBA-200

---

e2e-tests/steps/beforeYouStartSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/before_you_apply/referrer_details/confirmDetailsPage.ts
integration_tests/pages/apply/before_you_apply/referrer_details/contactNumberPage.ts
integration_tests/pages/apply/before_you_apply/referrer_details/jobTitlePage.ts
integration_tests/pages/apply/before_you_apply/referrer_details/locationPage.ts
integration_tests/tests/apply/before_you_apply/referrer-details/confirm_details.cy.ts
integration_tests/tests/apply/before_you_apply/referrer-details/contact_number.cy.ts
integration_tests/tests/apply/before_you_apply/referrer-details/job_title.cy.ts
integration_tests/tests/apply/before_you_apply/referrer-details/location.cy.ts
server/form-pages/apply/before-you-start/referrer-details/contactNumber.test.ts
server/form-pages/apply/before-you-start/referrer-details/contactNumber.ts
server/form-pages/apply/before-you-start/referrer-details/index.ts
server/form-pages/apply/before-you-start/referrer-details/location.test.ts
server/form-pages/apply/before-you-start/referrer-details/location.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/referrer-details/location.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-361
- Adds new 'where are you based?' in referrer details task
- backfills integration tests for the other pages in the task
confirm:

CBA-361 build where are you based page

---

e2e-tests/steps/offenceAndLicenceInformationSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/offence-information/alleged-offences/allegedOffenceDataPage.ts
integration_tests/pages/apply/offence-information/alleged-offences/allegedOffencesPage.ts
integration_tests/pages/apply/offence-information/alleged-offences/allegedOffencesSummaryPage.ts
integration_tests/tests/apply/offence-information/alleged-offences-data.cy.ts
integration_tests/tests/apply/offence-information/alleged-offences-summary.cy.ts
integration_tests/tests/apply/offence-information/alleged-offences.cy.ts
server/form-pages/apply/offence-information/alleged-offences/allegedOffences.test.ts
server/form-pages/apply/offence-information/alleged-offences/allegedOffences.ts
server/form-pages/apply/offence-information/alleged-offences/allegedOffencesSummary.test.ts
server/form-pages/apply/offence-information/alleged-offences/allegedOffencesSummary.ts
server/form-pages/apply/offence-information/alleged-offences/custom-forms/allegedOffenceData.test.ts
server/form-pages/apply/offence-information/alleged-offences/custom-forms/allegedOffenceData.ts
server/form-pages/apply/offence-information/alleged-offences/index.ts
server/form-pages/utils/questions.ts
server/utils/applications/utils.ts
server/views/applications/pages/alleged-offences/alleged-offence-data.njk
server/views/applications/pages/alleged-offences/alleged-offences-summary.njk
server/views/applications/pages/alleged-offences/alleged-offences.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-440?atlOrigin=eyJpIjoiMjVmYjJhN2NiNjQxNGY1NTg5M2ZmNmQ2MjU4NWZlNGMiLCJwIjoiaiJ9)
* Add alleged offences summary page
* Update content on alleged offences and data pages
* Add missing integration tests
confirm:

Update alleged offences pages

---

integration_tests/pages/apply/submit_application/applicationSubmittedPage.ts
server/views/applications/confirm.njk

https://dsdmoj.atlassian.net/browse/CBA-370
https://dsdmoj.atlassian.net/browse/CBA-371
Updates content of submission complete page
COURT
PRISON
COURT
PRISON
confirm:

feat: updates the submission complete page for court and prison

---

server/views/static/privacy-notice.njk

https://dsdmoj.atlassian.net/browse/CBA-357
Really minor text changes in the privacy notice
Really are minor and the page image would be huge
confirm:

Cba 357 updates to privacy notice

---

helm_deploy/hmpps-community-accommodation-tier-2-bail-ui/values.yaml

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-451?atlOrigin=eyJpIjoiY2VhNjczZGM2NjMyNDE3YjhiYTg1MTc5ZWUwMTI4ZWYiLCJwIjoiaiJ9)
The service name utilises IAM roles for granted permissions. This is
required to interface with AWS SQS where our audit logs are sent.
A corresponding PR for cloud platform has been raised:
https://github.com/ministryofjustice/cloud-platform-environments/pull/31417
confirm:

Set service account name to access AWS resources

---

e2e-tests/steps/areaAndFundingSection.ts
integration_tests/fixtures/applicationDocument.json
server/form-pages/apply/area-and-funding/area-information/exclusionZones.test.ts
server/form-pages/apply/area-and-funding/area-information/exclusionZones.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/area-information/exclusion-zones.njk
server/views/applications/pages/check-your-answers/check-your-answers.njk
server/views/applications/pages/layout.njk
server/views/applications/pages/risk-information/concerns.njk

https://dsdmoj.atlassian.net/browse/CBA-343
Text updates to the page
confirm:

feat: updates to the exclusions page

---

e2e-tests/steps/apply.ts
e2e-tests/steps/offenceAndLicenceInformationSection.ts
e2e-tests/tests/01_apply_as_nomis_prison_user.spec.ts
e2e-tests/tests/02_apply_as_nomis_court_user.spec.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/offence-information/provide-offences-and-convictions-details/offencesAndConvictionsGuidancePage.ts
integration_tests/tests/apply/offence-information/offence-and-convictions-guidance.cy.ts
server/form-pages/apply/offence-information/index.ts
server/form-pages/apply/offence-information/provide-offences-and-convictions-details/index.ts
server/form-pages/apply/offence-information/provide-offences-and-convictions-details/offencesAndConvictionsGuidance.test.ts
server/form-pages/apply/offence-information/provide-offences-and-convictions-details/offencesAndConvictionsGuidance.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/provide-offences-and-convictions-details/offences-and-convictions-guidance.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-376?atlOrigin=eyJpIjoiZmRiYjBjY2M3NTYzNDFmZTk1OGQyNWExNmFmMDEzNDciLCJwIjoiaiJ9)
Adds the new task and guidance page
confirm:

Introduce offences and convictions guidance task

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Preprod and prod must have the allow list set to null so that MFA will work correctly
Once merged @adamhughes86 will deploy to preprod and prod and test the MFA

Remove Preprod and prod allow list

---

server/data/stubs/application-statuses.json

https://dsdmoj.atlassian.net/browse/CBA-469
Text changed
confirm:

made the text change required by the JIRA ticket

---

server/views/reports/new.njk

https://dsdmoj.atlassian.net/browse/CBA-458
Added two fields in first example. One field in second. One field in third.
confirm:

added new data fields in ui content when downloading reports

---

server/utils/nunjucksSetup.ts

https://dsdmoj.atlassian.net/browse/CBA-420
Changed service name heading text
confirm:

changed the heading

---

integration_tests/pages/index.ts
server/controllers/dashboardController.test.ts
server/controllers/dashboardController.ts

https://dsdmoj.atlassian.net/browse/CBA-372
confirm:

changed the service name in the dashboard to match the ticket

---

integration_tests/tests/health.cy.ts
server/app.ts
server/middleware/setUpHealthChecks.ts

In order to validate that sentry is working I've added the health check tests and the debugging url

Add tests for sentry

---

server/utils/phaseBannerUtils.test.ts
server/utils/phaseBannerUtils.ts

https://dsdmoj.atlassian.net/browse/CBA-433
Just a link change
Life is too short
confirm:

fix: update link for feedback form

---

server/views/applications/before-you-start.njk

https://dsdmoj.atlassian.net/browse/CBA-432
One char! y oh y
confirm:

fix: typo fix in b4 u start page

---

e2e-tests/steps/offenceAndLicenceInformationSection.ts
e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationDocument.json
integration_tests/tests/apply/risks-and-needs/risk-information/complete_acct_data_page.cy.ts
integration_tests/tests/apply/risks-and-needs/risk-information/complete_acct_page.cy.ts
server/form-pages/apply/offence-information/community-supervision-and-current-offences/index.ts
server/form-pages/apply/risks-and-needs/index.ts
server/form-pages/apply/risks-and-needs/risk-information/index.ts
server/utils/assessUtils.test.ts

https://dsdmoj.atlassian.net/browse/CBA-467
confirm:

text changes as outlined in JIRA CBA-467

---

server/form-pages/utils/questions.ts
server/views/applications/pages/area-information/_preferred-area.njk

https://dsdmoj.atlassian.net/browse/CBA-341
https://dsdmoj.atlassian.net/browse/CBA-342
Text updates on the area pages 
confirm:

feat: first and second area preferrence page updates

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/pages/apply/risks_and_needs/health-needs/substanceMisusePage.ts
server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts
server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts
server/views/applications/pages/health-needs/_health-needs-screen.njk

https://dsdmoj.atlassian.net/browse/CBA-421
Updates nav for subst misuse
confirm:

feat: update nav on alcohol an dsubst misuse

---

e2e-tests/steps/aboutThePersonSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/about_the_person/address_history/previousAddressPage.ts
integration_tests/tests/apply/about_the_person/address_history/previous_address.cy.ts
server/form-pages/apply/about-the-person/address-history/previousAddress.test.ts
server/form-pages/apply/about-the-person/address-history/previousAddress.ts
server/form-pages/utils/questions.ts
server/utils/applications/deleteOrphanedData.test.ts
server/utils/applications/deleteOrphanedData.ts
server/views/applications/pages/address-history/previous-address.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-363
Updates previous address page in line with the updated designs.
confirm:

CBA-363: change address history screen

---

server/form-pages/utils/questions.ts

https://dsdmoj.atlassian.net/browse/CBA-522
Changes answers on the page
confirm:

fix updates answers on Any Previous Convictions page

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/pages/apply/risks_and_needs/health-needs/substanceMisusePage.ts
server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts
server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts
server/views/applications/pages/health-needs/_health-needs-screen.njk

https://dsdmoj.atlassian.net/browse/CBA-421
Minor wording tweaks
confirm:

fix: wording tweak on subst misuse page

---

e2e-tests/steps/offenceAndLicenceInformationSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/offence-information/probation-supervision-details/oasysRiskAssessmentDetailsPage.ts
integration_tests/tests/apply/offence-information/probation-supervision-details/oasys-risk-assessment-details.cy.ts
integration_tests/tests/apply/offence-information/probation-supervision-details/oasys-risk-assessment.cy.ts
server/form-pages/apply/offence-information/add-probation-supervision-details/index.ts
server/form-pages/apply/offence-information/add-probation-supervision-details/oasysRiskAssessment.test.ts
server/form-pages/apply/offence-information/add-probation-supervision-details/oasysRiskAssessment.ts
server/form-pages/apply/offence-information/add-probation-supervision-details/oasysRiskAssessmentDetails.test.ts
server/form-pages/apply/offence-information/add-probation-supervision-details/oasysRiskAssessmentDetails.ts
server/form-pages/utils/questions.ts
server/utils/applications/deleteOrphanedData.test.ts
server/utils/applications/deleteOrphanedData.ts
server/views/applications/pages/add-probation-supervision-details/oasys-risk-assessment-details.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-305?atlOrigin=eyJpIjoiYzlkMDc0YWEyZjUyNDlmMmFiY2VlZTMxOTc4YzZmNGIiLCJwIjoiaiJ9)
* Introduce risk assessment details page
* Ensure stale risk data is removed when dependant answers are changed
confirm:

[CBA-305] Introduce risk assessment details page

---

server/data/restClient.ts

This is to help differentiate cas2 bail requests to the API, which can then be easily triaged.
confirm:

Send X-SERVICE-NAME header on all requests

---

integration_tests/tests/apply/create_application/find_by_prison_number.cy.ts
server/@types/ui/index.d.ts
server/controllers/apply/applicationsController.test.ts
server/controllers/apply/applicationsController.ts
server/controllers/peopleController.test.ts
server/controllers/peopleController.ts
server/utils/validation.test.ts
server/utils/validation.ts
server/views/applications/search-by-crn.njk
server/views/applications/search-by-prison-number.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-559?atlOrigin=eyJpIjoiMzE5NGU2N2FlNjk0NDM5NjkyNzYwNzg5MTFkNDdmZDAiLCJwIjoiaiJ9)
Currently, to start an application for prison bail, the service relies on the following:
1. A Prison Referrer entering the prison number of the applicant,
2. The applicant has a corresponding record in nDelius, and;
3. these two records within Nomis and nDelius are linked (manually or automatically)
Not all applicants will have linked records across nDelius and Nomis,
leading to prison referrers encountering a 404 error when searching via
prison number.
Therefore, we want to allow them search via CRN if they encounter a 404.
Short-term fix:
To mitigate the issue, we are tweaking the error message for all 404s
encountered when searching via prison number to direct …

[CBA-559] Allow prison bail referrer to search by CRN

---

server/utils/checkYourAnswersUtils.test.ts
server/utils/checkYourAnswersUtils.ts

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-521?atlOrigin=eyJpIjoiZDBiODZmOWRjZmE3NDRhZWI5MzI3NzAwYzQzNDljMTMiLCJwIjoiaiJ9)
Display 'Unable to import' when PNC number is missing
confirm:

Display 'Unable to import' when PNC number is missing

---

server/form-pages/apply/about-the-person/address-history/previousAddress.test.ts
server/form-pages/utils/questions.ts

https://dsdmoj.atlassian.net/browse/CBA-548
confirm:
- [ x] Are any changes required to the e2e tests?
- [x ] If you've added a new route, have you added a new
- [x ] Are there environment variables or other infrastructure configuration which needs to be included in this release?
- [ x] Are there any data migrations required. Automatic or manual?
- [x ] Does this rely on changes being deployed to the CAS API?

fixed typo

---

e2e-tests/pages/apply/findByPrisonNumberPage.ts
integration_tests/pages/apply/findByPrisonNumberPage.ts
integration_tests/tests/apply/create_application/find_by_prison_number.cy.ts
server/controllers/apply/applicationsController.test.ts
server/controllers/apply/applicationsController.ts
server/views/applications/before-you-start.njk
server/views/applications/search-by-prison-number.njk

https://dsdmoj.atlassian.net/browse/CBA-198
confirm:

fix: wording on search by mons page

---

integration_tests/pages/apply/applicationOriginPage.ts
server/controllers/apply/applicationsController.test.ts
server/controllers/apply/applicationsController.ts
server/views/applications/application-origin.njk

https://dsdmoj.atlassian.net/browse/CBA-194
confirm:

made text changes and updated tests

---

server/views/applications/pages/check-your-answers/check-your-answers.njk
server/views/applications/pages/layout.njk
server/views/applications/pages/previous-unspent-convictions/unspent-convictions-data.njk
server/views/applications/pages/risk-information/concerns.njk

https://dsdmoj.atlassian.net/browse/CBA-578
confirm:

Changed Exit without saving to Back to task list

---

server/views/applications/before-you-start.njk
server/views/applications/pages/health-needs/health-needs-information.njk
server/views/applications/pages/risk-information/concerns.njk

https://dsdmoj.atlassian.net/browse/CBA-196
confirm:

made text tweaks as per JIRA ticket

---

server/views/applications/search-by-prison-number.njk

https://dsdmoj.atlassian.net/browse/CBA-198
confirm:

changed the CRN as requested in JIRA ticket

---

server/views/applications/search-by-crn.njk

https://dsdmoj.atlassian.net/browse/CBA-196
confirm:

changed the CRN to match the JIRA AC

---

e2e-tests/pages/basePage.ts
e2e-tests/steps/areaAndFundingSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/area-and-funding/area-information/gangAffiliationsPage.ts
integration_tests/tests/apply/area-and-funding/area-information/gang-affiliations.cy.ts
server/form-pages/apply/area-and-funding/area-information/gangAffiliations.test.ts
server/form-pages/apply/area-and-funding/area-information/gangAffiliations.ts
server/form-pages/utils/questions.ts
server/views/applications/pages/area-information/gang-affiliations.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-365
- updates gang affiliations page with new designs
- adds integration tests for exclusion zones and preferred areas task
confirm:

Cba 365 make changes to gang affiliations page

---

integration_tests/pages/apply/area-and-funding/area-information/gangAffiliationsPage.ts
server/form-pages/apply/area-and-funding/area-information/gangAffiliations.test.ts
server/form-pages/apply/area-and-funding/area-information/gangAffiliations.ts

Fix gang affiliations page title

---

e2e-tests/pages/apply/applicationOriginPage.ts
server/views/applications/application-origin.njk

https://dsdmoj.atlassian.net/browse/CBA-194
confirm:

Cba 194 amend you are applying for court or prison bail page to where are you making the application from page text change buttons

---

e2e-tests/steps/areaAndFundingSection.ts

Fix gang affiliation page title in E2E tests

---

server/form-pages/utils/questions.ts

https://dsdmoj.atlassian.net/browse/CBA-413
confirm:

linter complained after the merge fixed

---

server/form-pages/apply/bail-information/bail-conditions/nonStandardBailConditions.test.ts
server/form-pages/apply/bail-information/bail-conditions/nonStandardBailConditions.ts

I think I missed the validation designs on the previous ticket, so I've introduced it here.
confirm:

Add validation on non-standard bail conditions page

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/risks-and-needs/risk-information/informationSourcesPage.ts
integration_tests/pages/apply/risks_and_needs/health-needs/informationSourcesPage.ts
integration_tests/tests/apply/risks-and-needs/risk-information/complete_risk_management_arrangements_page.cy.ts
integration_tests/tests/apply/risks-and-needs/risk-information/information_sources.cy.ts
integration_tests/tests/apply/risks_and_needs/health-needs/information_sources.cy.ts
server/form-pages/apply/risks-and-needs/health-needs/index.ts
server/form-pages/apply/risks-and-needs/health-needs/informationSources.test.ts
server/form-pages/apply/risks-and-needs/health-needs/informationSources.ts
server/form-pages/apply/risks-and-needs/health-needs/otherHealth.test.ts
server/form-pages/apply/risks-and-needs/health-needs/otherHealth.ts
server/form-pages/apply/risks-and-needs/risk-information/index.ts
server/form-pages/apply/risks-and-needs/risk-information/informationSources.test.ts
server/form-pages/apply/risks-and-needs/risk-information/informationSources.ts
server/form-pages/apply/risks-and-needs/risk-information/riskManagementArrangements.test.ts
server/form-pages/apply/risks-and-needs/risk-information/riskManagementArrangements.ts
server/form-pages/utils/questions.ts
server/utils/checkYourAnswersUtils.test.ts
server/views/applications/pages/health-needs/_health-needs-screen.njk
server/views/applications/pages/health-needs/information-sources.njk
server/views/applications/pages/risk-information/_risk-information-screen.njk
server/views/applications/pages/risk-information/information-sources.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-367
confirm:

CBA-367: build pages on information sources for health and risk sections

---

server/form-pages/apply/about-the-person/personal-information/gender.test.ts
server/form-pages/apply/about-the-person/personal-information/gender.ts

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-430
confirm:

Update gender page error message

---

server/form-pages/apply/risks-and-needs/risk-information/acct.test.ts
server/form-pages/apply/risks-and-needs/risk-information/acct.ts
server/form-pages/apply/risks-and-needs/risk-information/custom-forms/addAcctNote.test.ts
server/form-pages/apply/risks-and-needs/risk-information/custom-forms/addAcctNote.ts

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-249?atlOrigin=eyJpIjoiNzU3NzMyMTJkNTA1NGY0NmEzMzBlZDMzOTkzZThhMGIiLCJwIjoiaiJ9)
* Adds missing date validation
* Ensure referring institution is rendered on the check your answers page
confirm:

[CBA-249] Fixes for Add ACCT note page

---

server/form-pages/apply/offences-and-concerns/add-probation-supervision-details/contactedCppAboutCurrentRiskLevels.test.ts
server/form-pages/apply/offences-and-concerns/add-probation-supervision-details/contactedCppAboutCurrentRiskLevels.ts

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-593?atlOrigin=eyJpIjoiOGVmZjhhZjQzMjRjNDZmOWFiM2IxNGM2MDZkNDQyOWMiLCJwIjoiaiJ9)
Update the validation messages to be clearer.
confirm:

Change contactDate validation

---

server/views/applications/pages/alleged-offences/alleged-offences-summary.njk

Content tweaks on alleged offences summary page

---

integration_tests/fixtures/applicationData.json
server/utils/applicationUtils.test.ts

Change referrer name in test mock data
confirm:

Change referrer name in test mock data

---

helm_deploy/hmpps-community-accommodation-tier-2-bail-ui/values.yaml
logger.ts
server/config.ts
server/errorHandler.ts
server/middleware/auditMiddleware.test.ts
server/middleware/auditMiddleware.ts
server/middleware/populateCurrentUser.ts
server/middleware/setUpCurrentUser.ts
server/utils/nunjucksSetup.ts

* Remove potential PII from being logged
* Make error messages more ambiguous
* Set 'info' to be the default logging level
confirm:

Logging audit updates

---

e2e-tests/steps/areaAndFundingSection.ts

Fix e2e tests for gang affiliations page

---

assets/scss/application.scss
assets/scss/components/_application-summary-panel.scss
assets/scss/components/_submitted-application-panel.scss
server/views/components/applicationSummary/macro.njk

Jira: https://dsdmoj.atlassian.net/browse/CBA-610
Fixes focus text colour on application summary panel to ensure contrast accessibility requirements are met.
confirm:

CBA-610: change focus state text colour in submitted application view

---

server/form-pages/apply/offences-and-concerns/risk-information/concerns.test.ts
server/form-pages/apply/offences-and-concerns/risk-information/concerns.ts
server/views/applications/pages/alleged-offences/alleged-offence-data.njk
server/views/applications/pages/previous-unspent-convictions/unspent-convictions-data.njk
server/views/applications/pages/risk-information/add-acct-note.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-666
- Adds missing back link on concerns information cover page
- Ensures consistent 'Cancel' and 'Back to task list' links on all our 'add another' pages
confirm:

CBA-666 add missing back links

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/health_needs/health-needs/communicationAndLanguagePage.ts
integration_tests/pages/apply/health_needs/health-needs/communicationAndLanguageRelevanceCheckPage.ts
integration_tests/tests/apply/health-needs/health-needs/communication_and_language.cy.ts
integration_tests/tests/apply/health-needs/health-needs/mental_health.cy.ts
server/form-pages/apply/health-needs/health-needs/communicationAndLanguage.test.ts
server/form-pages/apply/health-needs/health-needs/communicationAndLanguage.ts
server/form-pages/apply/health-needs/health-needs/communicationAndLanguageRelevanceCheck.test.ts
server/form-pages/apply/health-needs/health-needs/communicationAndLanguageRelevanceCheck.ts
server/form-pages/apply/health-needs/health-needs/index.ts
server/form-pages/apply/health-needs/health-needs/learningDifficulties.test.ts
server/form-pages/apply/health-needs/health-needs/learningDifficulties.ts
server/form-pages/apply/health-needs/health-needs/mentalHealth.test.ts
server/form-pages/apply/health-needs/health-needs/mentalHealth.ts
server/form-pages/utils/questions.ts
server/utils/applications/deleteOrphanedData.test.ts
server/utils/applications/deleteOrphanedData.ts
server/views/applications/pages/health-needs/_health-needs-screen.njk
server/views/applications/pages/health-needs/communication-and-language-relevance-check.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-635?atlOrigin=eyJpIjoiNTUzYmMzMGJmNTMzNGIzMzgzYzdmOGRhZTBkNjc4Y2UiLCJwIjoiaiJ9)
If an applicant does not have communication and language needs, skip these questions.
confirm:

Introduce relevance check for communication and language needs

---

server/form-pages/apply/health-needs/health-needs/communicationAndLanguage.test.ts
server/form-pages/apply/health-needs/health-needs/communicationAndLanguage.ts
server/views/applications/pages/health-needs/communication-and-language-relevance-check.njk

[JIRA](https://dsdmoj.atlassian.net/browse/CBA-635?atlOrigin=eyJpIjoiZmViNTAyMWM4OWUzNDg1MTk0ZDllNmZiYjFmY2FiMjYiLCJwIjoiaiJ9)
* Add guidance to communication and language page
* Amend error messages
confirm:

CBA-635 add communication and language guidance

---

server/form-pages/apply/health-needs/health-needs/brainInjuryDetails.test.ts
server/form-pages/apply/health-needs/health-needs/brainInjuryDetails.ts
server/form-pages/utils/questions.ts

Correct brain injury details page copy

---

server/form-pages/utils/questions.ts
server/views/applications/pages/previous-unspent-convictions/any-previous-convictions.njk

Content tweaks

---

e2e-tests/pages/apply/dashboardPage.ts
e2e-tests/steps/prisonDashboard.ts
e2e-tests/tests/05_prison_dashboard.spec.ts

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-701
Adds a basic E2E test to test the journey to the new prison dashboard and into an application from the prison dashboard.
confirm:

Add E2E test for prison dashboard

---

integration_tests/tests/apply/about_the_person/personal-information/gender.cy.ts
server/form-pages/apply/about-the-person/personal-information/gender.test.ts
server/form-pages/apply/about-the-person/personal-information/gender.ts
server/utils/nunjucksSetup.ts
server/utils/personUtils.test.ts
server/utils/personUtils.ts

Jira ticket
This PR removes the conditional logic checking if applicant is registered as female before directing the referrer to the pregnancy information page. This is so that all applicant complete this page, making the service more accessible.
confirm:

CBA-706: the is the applicant pregnant question is shown in all applications

---

server/utils/phaseBannerUtils.test.ts
server/utils/phaseBannerUtils.ts

[This](https://dsdmoj.atlassian.net/browse/CBA-717) was to update the link in the phase banner to a new survey
confirm:

Update feedback survey link in phasebanner

---

server/utils/phaseBannerUtils.test.ts
server/utils/phaseBannerUtils.ts

[This](https://dsdmoj.atlassian.net/browse/CBA-719) was to update the email address in the phase banner and the accessibility statement.
confirm:

Update email address in accessibility and phase banner

---

server/utils/phaseBannerUtils.test.ts
server/utils/phaseBannerUtils.ts

[This](https://dsdmoj.atlassian.net/browse/CBA-720) was to update the contents of the phase banner.
confirm:

Update phase banner content

---

e2e-tests/pages/apply/dashboardPage.ts

This fixes a failing e2e test.
confirm:

Update text for viewing prison bail applications on dashboard

---

e2e-tests/steps/risksAndNeedsSection.ts
integration_tests/fixtures/applicationData.json
integration_tests/pages/apply/offences-and-concerns/risk-information/detailsOfDomesticAbuseConcernsPage.ts
integration_tests/pages/apply/offences-and-concerns/risk-information/domesticAbuseConcernsPage.ts
integration_tests/tests/apply/offences-and-concerns/risk-information/complete-details-of-domestic-abuse-concerns-page.cy.ts
integration_tests/tests/apply/offences-and-concerns/risk-information/complete-does-the-applicant-have-acct-notes-page.cy.ts
integration_tests/tests/apply/offences-and-concerns/risk-information/complete-domestic-abuse-concerns-page.cy.ts
integration_tests/tests/apply/offences-and-concerns/risk-information/complete_acct_page.cy.ts
server/form-pages/apply/offences-and-concerns/risk-information/acct.test.ts
server/form-pages/apply/offences-and-concerns/risk-information/acct.ts
server/form-pages/apply/offences-and-concerns/risk-information/detailsOfDomesticAbuseConcerns.test.ts
server/form-pages/apply/offences-and-concerns/risk-information/detailsOfDomesticAbuseConcerns.ts
server/form-pages/apply/offences-and-concerns/risk-information/doesTheApplicantHaveAcctNotes.test.ts
server/form-pages/apply/offences-and-concerns/risk-information/doesTheApplicantHaveAcctNotes.ts
server/form-pages/apply/offences-and-concerns/risk-information/domesticAbuseConcerns.test.ts
server/form-pages/apply/offences-and-concerns/risk-information/domesticAbuseConcerns.ts
server/form-pages/apply/offences-and-concerns/risk-information/index.ts
server/form-pages/apply/offences-and-concerns/risk-information/violenceAndArson.test.ts
server/form-pages/apply/offences-and-concerns/risk-information/violenceAndArson.ts
server/form-pages/utils/questions.ts
server/utils/applications/deleteOrphanedData.test.ts
server/utils/applications/deleteOrphanedData.ts
server/utils/checkYourAnswersUtils.test.ts
server/views/applications/pages/risk-information/_risk-information-screen.njk
server/views/applications/pages/risk-information/details-of-domestic-abuse-concerns.njk
server/views/applications/pages/risk-information/domestic-abuse-concerns.njk

Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-585
**This work is blocked whilst we wait for confirmation that we can collect this information as part of the application.**
Adds new domestic abuse question pages, with a relevance check followed by a details page if concerns are present.
confirm:

CBA-585 create an explicit question set that will gather information needed about domestic violence

---

e2e-tests/tests/05_prison_dashboard.spec.ts
integration_tests/mockApis/applications.ts
integration_tests/pages/page.ts
integration_tests/tests/apply/prison_applications.cy.ts
server/@types/shared/models/Cas2v2ApplicationSummary.ts
server/controllers/apply/applicationsController.test.ts
server/controllers/apply/applicationsController.ts
server/data/applicationClient.test.ts
server/data/applicationClient.ts
server/services/applicationService.ts
server/testutils/factories/applicationSummary.ts
server/utils/applicationUtils.test.ts
server/utils/applicationUtils.ts
server/views/applications/prison-applications.njk

https://dsdmoj.atlassian.net/browse/CBA-709
updated endpoint for all prison applications

feat(bail): updated endpoint for all prison applications

---

integration_tests/pages/page.ts
server/config.ts
server/utils/applicationUtils.test.ts
server/utils/applicationUtils.ts

Jira: https://dsdmoj.atlassian.net/browse/CBA-725 and https://dsdmoj.atlassian.net/browse/CBA-724
- reenables the prison dashboard feature flag
- corrects the prison dashboard data rows to reflect the changed column order that was previously introduced.
confirm:

Cba 725 re enable feature flag on view all prison bail applications
