rename-project.bash
CircleCI is not being used now and the rename project script references a file that does not exist
=> Updating rename project script as circleCI is no recommended

integration_tests/pages/index.ts
Missed the note and the failed test from https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui/pull/15, so this fixes that
=> Fixed a missing change to Bail wording in an integration test

esbuild-configs/esbuild.config.js
I think ESbuild is currently configured to copy only TS files over from the server directory, as well as anything else we explicitly declare. We may want to update this later to copy all non-test files but for now we can just explicitly copy across the i18n directory.
confirm:
=> Include i18n directory in ES build config

.github/workflows/pipeline.yml
In a recent change, we temporarily skipped the integration test step until the full test suite is in place. As subsequent jobs relied on the tests, this stopped Github Actions deploying to dev. This change ensures we deploy regardless of the integration test step.
confirm:
=> Ensure app deploys to dev even with integration tests skipped

server/controllers/dashboardController.ts, server/utils/userUtils.test.ts, server/utils/userUtils.ts
Copies over HDC code to conditionally render dashboard tiles based on user roles.
NB This will render no tiles for assessors, as within HDC they have not been given tiles on the index page dashboard - instead they are given links to specific applications or their own assessor dashboard.
confirm:
=> Customise dashboard tiles based on user roles

server/views/applications/pages/confirm-eligibility/confirm-eligibility.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-45
confirm:
=> Remove HDC guidance from confirm eligibility page

server/utils/nunjucksSetup.ts
Quick change to swap the default set title of the service that appears in the header and on the dashboard
=> Swapping the title of the service to be a more friendly bail version

.github/workflows/security_npm_dependency.yml, .github/workflows/security_trivy.yml, .github/workflows/security_veracode_pipeline_scan.yml, .github/workflows/security_veracode_policy_scan.yml
Fix for HEAT-473 - incorrect slack channel in Security scan notifications.
=> fix/udate slack security alerts slack channel to #cas-events

server/views/applications/before-you-start.njk
We aren’t sure what we want on this page, but we think we will want something, so for now we’re keeping the page but removing the content.
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-93.
confirm:
=> Strip out guidance text from start application page

assets/scss/application.scss
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-102?atlOrigin=eyJpIjoiZTZlMWM0ZTUyZDVmNDY4OGEwYmEyMmRkMWZlYmViYmUiLCJwIjoiaiJ9)
confirm:
=> Fix heading styling on alternative ID page

e2e-tests/steps/risksAndNeedsSection.ts, server/form-pages/apply/risks-and-needs/health-needs/brainInjury.test.ts, server/form-pages/apply/risks-and-needs/health-needs/brainInjury.ts, server/form-pages/apply/risks-and-needs/health-needs/guidance.test.ts, server/form-pages/apply/risks-and-needs/health-needs/guidance.ts, server/form-pages/apply/risks-and-needs/health-needs/liaisonAndDiversion.test.ts, server/form-pages/apply/risks-and-needs/health-needs/liaisonAndDiversion.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.test.ts, server/form-pages/apply/risks-and-needs/health-needs/substanceMisuse.ts, server/views/applications/pages/health-needs/_health-needs-screen.njk, server/views/applications/pages/health-needs/guidance.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-103
Moves L&D page to the top of the health needs task, in line with the paper form.
confirm:
=> CBA-103: move Liaison and Diversion page to top of health needs task

server/views/applications/pages/risk-of-serious-harm/_risk-of-serious-harm-screen.njk
As we’re no longer importing from OASys, we don’t have a RoSH summary page.
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-104
confirm:
=> CBA-104: Remove redundant RoSH summary link

server/form-pages/apply/bail-information/bail-hearing-arrangement/bailHearingArranger.test.ts, server/form-pages/apply/bail-information/bail-hearing-arrangement/bailHearingArranger.ts
If the applicant is arranging the bail hearing themselves, we redirect the user back to the task list.
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-105
confirm:
=> CBA-105: Only redirect user to legal advisor info if they select legal advisor

package-lock.json, package.json
Express was using vulnerable version of path-to-regexp. This patch version of express updates path-to-regexp dependency to the newer version which no longer includes the vulnerability.
```
$ npm run security_audit                                                                                                
> hmpps-community-accommodation-tier-2-bail-ui@0.0.1 security_audit
> npx audit-ci --config audit-ci.json
NPM audit report results:
{
"advisories": {
"express": {
"name": "express",
"severity": "moderate",
"isDirect": true,
"via": [
"path-to-regexp"
],
"effects": [],
"range": "4.0.0-rc1 - 4.21.1 || 5.0.0-alpha.1 - 5.0.0-beta.3",
"nodes": [
"node_modules/express"
],
"fixAvailable": true
},
"path-to-regexp": {
"name": "path-to-regexp",
"severity": "moderate",
"isDirect": false,
"via": [ …
```
=> SECURITY: Update express from 4.21.1 to 4.21.2

server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskToOthers.test.ts, server/form-pages/apply/risks-and-needs/risk-of-serious-harm/riskToOthers.ts
This page previously linked to the RoSH summary page, which has been removed from the service.
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-113
confirm:
=> Fix back link from risk to others page

e2e-tests/steps/apply.ts, e2e-tests/steps/beforeYouStartSection.ts, server/form-pages/apply/before-you-start/solicitor-details/contactInformation.test.ts, server/form-pages/apply/before-you-start/solicitor-details/contactInformation.ts, server/form-pages/apply/before-you-start/solicitor-details/hasSolicitor.test.ts, server/form-pages/apply/before-you-start/solicitor-details/hasSolicitor.ts, server/form-pages/apply/before-you-start/solicitor-details/index.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/solicitor-details/has-solicitor.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-117
Adds a new page to the start of the solicitor details task, checking that the applicant has a solicitor. If they do, the referrer continues to the solicitor details. If not, the task is complete and they return to the task list.
confirm:
=> CBA-117 add a new page at the start of add solicitor details task for does the applicant have a solicitor

server/utils/userUtils.test.ts, server/utils/userUtils.ts
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-47?atlOrigin=eyJpIjoiYWIwNWY5MzM2ZTc0NDE4ZWI1YzU2M2QzNDhkZmU0M2IiLCJwIjoiaiJ9)
We want probation users to be shown the appropriate tiles on the service home page so that they can create and view applications.
Allow probation users to start and view applications
confirm:
=> Allow probation users to start and view applications

server/utils/checkYourAnswersUtils.test.ts, server/utils/checkYourAnswersUtils.ts
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-124
Adds application type to the view application table, displayed on the CYA screen as well as the submitted application screens.
NB this is waiting for applicationOrigin to be available as part of the Cas2v2SubmittedApplication, so should not be merged until that API update is in main.
confirm:
=> Add application type to view application table

server/views/partials/layout.njk, server/views/static/cookies-policy.njk
This was copied over from CAS2 HDC but is not needed in the new Bail service.
=> Remove google tag manager

e2e-tests/steps/aboutThePersonSection.ts, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/about_the_person/personal_information/genderPage.ts, integration_tests/pages/apply/about_the_person/personal_information/immigrationStatusPage.ts, integration_tests/pages/apply/about_the_person/personal_information/pregnancyInformationPage.ts, integration_tests/pages/apply/about_the_person/personal_information/supportWorkerPreferencePage.ts, integration_tests/pages/apply/about_the_person/personal_information/workingMobilePhonePage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/about_the_person/personal-information/gender.cy.ts, integration_tests/tests/apply/about_the_person/personal-information/immigration_status.cy.ts, integration_tests/tests/apply/about_the_person/personal-information/pregnancy_information.cy.ts, integration_tests/tests/apply/about_the_person/personal-information/support_worker_preference.cy.ts, integration_tests/tests/apply/about_the_person/personal-information/working_mobile_phone.cy.ts, server/form-pages/apply/about-the-person/personal-information/gender.test.ts, server/form-pages/apply/about-the-person/personal-information/gender.ts, server/form-pages/apply/about-the-person/personal-information/immigrationStatus.test.ts, server/form-pages/apply/about-the-person/personal-information/immigrationStatus.ts, server/form-pages/apply/about-the-person/personal-information/index.ts, server/form-pages/apply/about-the-person/personal-information/pregnancyInformation.test.ts, server/form-pages/apply/about-the-person/personal-information/pregnancyInformation.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/personal-information/gender.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-303
Adds a new gender page to the personal information task, which presents after immigration status and before the two pages that are shown only for female applicants.
confirm:
=> CBA-303 create gender identity page in applicant details section

e2e-tests/steps/risksAndNeedsSection.ts, integration_tests/pages/apply/risks_and_needs/health-needs/brainInjuryPage.ts, integration_tests/pages/apply/risks_and_needs/health-needs/communicationAndLanguagePage.ts, integration_tests/pages/apply/risks_and_needs/health-needs/independentLivingPage.ts, integration_tests/pages/apply/risks_and_needs/health-needs/learningDifficultiesPage.ts, integration_tests/pages/apply/risks_and_needs/health-needs/liaisonAndDiversionPage.ts, integration_tests/pages/apply/risks_and_needs/health-needs/mentalHealthPage.ts, integration_tests/pages/apply/risks_and_needs/health-needs/otherHealthPage.ts, integration_tests/pages/apply/risks_and_needs/health-needs/physicalHealthPage.ts, integration_tests/pages/apply/risks_and_needs/health-needs/substanceMisusePage.ts, integration_tests/pages/apply/risks_and_needs/utils.ts, integration_tests/tests/apply/risks_and_needs/health-needs/health_needs_information.cy.ts, integration_tests/tests/apply/risks_and_needs/health-needs/independent_living.cy.ts, integration_tests/tests/apply/risks_and_needs/health-needs/liaison_and_diversion.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/liaisonAndDiversion.test.ts, server/form-pages/apply/risks-and-needs/health-needs/liaisonAndDiversion.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/_health-needs-screen.njk, server/views/applications/pages/health-needs/liaison-and-diversion.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-280
- Updates L&D page title, hint text and answers
- Adds missing integration tests for health needs information page and independent living page
confirm:
=> CBA-280: add content to liaison and diversion assessment page

e2e-tests/steps/risksAndNeedsSection.ts, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks_and_needs/health-needs/communicationAndLanguagePage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/communication_and_language.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/communicationAndLanguage.test.ts, server/form-pages/apply/risks-and-needs/health-needs/communicationAndLanguage.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/communication-and-language.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-277
Updates communication and language needs page questions.
confirm:
=> CBA-277: change content on communication and language needs page

e2e-tests/steps/risksAndNeedsSection.ts, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks_and_needs/health-needs/brainInjuryPage.ts, integration_tests/tests/apply/risks_and_needs/health-needs/brain_injury.cy.ts, server/form-pages/apply/risks-and-needs/health-needs/brainInjury.test.ts, server/form-pages/apply/risks-and-needs/health-needs/brainInjury.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/health-needs/brain-injury.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-285
Updates the brain injury page questions.
I haven't altered the position of the heading as per the designs. That would require changes to all the health needs pages so I'll add a ticket to the backlog for that.
confirm:
=> CBA-285: change content on brain injury details for applicant page

.github/workflows/pipeline.yml
A recent change to the one of the github actions we rely on for
deployment has changed the way the input for the environment is
accessed[1].
Previously, our workflow would default to `dev` which would correctly
retrieve our yaml file, however, as this is now accessing directly from
the explicitly set input, we need those to match.
[1]https://github.com/ministryofjustice/hmpps-github-actions/commit/2e7fb60d746fa9f8ba079496f528af475531a0ec#diff-67584b6afa3fa98aadfae64e1d36cc98f7811b88407a04efd2c4c149489e2d51R117-R120
confirm:
Once we've merged it will be auto-deployed to the dev …
=> Rename deploy environment input

e2e-tests/steps/assess.ts, e2e-tests/tests/03_assess.spec.ts, server/utils/pagination.test.ts, server/utils/pagination.ts
In a previous commit[1], we attempted to mark this test as failing due to older application data resulting in a 404. However, this solution didn't work due to the test timing out.
Instead of marking as failing, we ensure the test chooses the most recent page of submitted applications which lowers the likelihood of selecting an older application.
A fix should still be implemented in the API to ensure all submitted applications are viewable.
[1]
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui/commit/70a5d85492703ba9d6b905a39aaed8b6577fb732#diff-429df44951dd618e2cda8caf7d8af4feca0e6dcdd8bc7b85339ae6c7623dda4dR8-R9
ready to be released at any point. Before merging to `main` we must …
=> Ensure assess e2e uses recent submitted application

helm_deploy/values-test.yaml
Cannot currently log into test. After speaking with auth team they recommend trying to replace the client creds in the test env
New client creds for test env
Once we've merged it will be auto-deployed to the dev environment. A manual push the test environment will need to be made to test this
=> New client creds for test env

package.json
Reverts ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui#78.
It slipped through but is causing dependency conflict errors. I think we may as well wait and see if Nunjucks updates the version of Chokidar it's using.
=> Revert "Update dependency chokidar to v4"

.github/workflows/e2e_tests.yml
Our [e2e test in github actions](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui/actions/runs/13925802562/job/38975285439) is reporting the following error
```
Error: Cannot find module '@playwright/test'
```
Which is due to the workflow not being able to retrieve the `node_modules` cache, even though the `integration_test` workflow is able to retrieve the cache with the exact same key.
```
Cache hit for: Linux-build-node-modules-8c55835dd02886b830d976f91098cb7ad63ae19fd9dde0a4277f2a860c749ddb
Received 218103808 of 263718395 (82.7%), 205.5 MBs/sec
Received 263718395 of 263718395 (100.0%), 209.4 MBs/sec
Cache Size: ~252 MB (263718395 B)
/usr/bin/tar -xf /home/runner/work/_temp/e07833c0-36[16](https://github.com/ministryofjustice/hmpps-community-accommodatio …
```
=> Install dependencies for e2e tests if cache fails

server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/controllers/peopleController.test.ts, server/controllers/peopleController.ts, server/utils/validation.test.ts, server/utils/validation.ts
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-374?atlOrigin=eyJpIjoiMjY5ZTg3NzcyZjBlNGViYjljYTM3YzI3Y2VkYzcxODYiLCJwIjoiaiJ9)
Previously, if you were to enter a CRN, and encounter an error creating
the application, you'd be bounced back to the prison number page. This
change implements:
* If applicationOrigin is courtBail, redirect to findByCrn page
* If applicationOrigin is prisonBail, redirect to findByPrisonNumber
page
* applicationOrigin is not known, redirect to applicationOrigin page
confirm:
=> Fix search by noms failure redirect

e2e-tests/steps/risksAndNeedsSection.ts, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/risks-and-needs/risk-information/livingInTheCommunityPage.ts, integration_tests/tests/apply/risks-and-needs/risk-information/complete_living_in_the_community_page.cy.ts, server/form-pages/apply/risks-and-needs/risk-information/livingInTheCommunity.test.ts, server/form-pages/apply/risks-and-needs/risk-information/livingInTheCommunity.ts, server/form-pages/utils/questions.ts, server/views/applications/pages/risk-information/living-in-the-community.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-264
Adds questions to living in the community page in the risk section.
confirm:
=> CBA-264 add content to living in the community page

package-lock.json, package.json
The previous version was causing a security alert: https://github.com/babel/babel/security/advisories/GHSA-968p-4wvh-cqc8. v7.26.0 patches this vulnerability.
As @babel/helpers isn’t a direct dependency, we need to use the override option in package.json.
confirm:
=> Fix @babel/helpers version to 7.26.0 or higher

helm_deploy/hmpps-community-accommodation-tier-2-bail-ui/values.yaml, helm_deploy/values-development.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
As this secret is not set in the test environment, deployments to test were failing with the error: secret "sqs-hmpps-audit-secret" not found.
We don't require audit logs in the test environment, so moving this secret to individual namespaces ensures test environment will not try to retrieve it.
In application code, the call to AWS SQS will silently fail, as logErrors is set to false by default[1].
[1]
https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui/blob/f943f18755b4c742d2ea8da48f0e04a0c1450fbe/server/services/auditService.ts#L44
confirm:
Once …
=> Move sqs-hmpps-audit-secret to individual namespaces

e2e-tests/steps/areaAndFundingSection.ts, integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/area-and-funding/funding-information/fundingCas2AccommodationPage.ts, integration_tests/tests/apply/area-and-funding/funding-information/complete_funding_cas2_accommodation.cy.ts, server/form-pages/apply/area-and-funding/funding-information/fundingCas2Accommodation.test.ts, server/form-pages/apply/area-and-funding/funding-information/fundingCas2Accommodation.ts, server/services/applicationService.test.ts, server/utils/applications/deleteOrphanedData.test.ts, server/utils/applications/deleteOrphanedData.ts, server/utils/checkYourAnswersUtils.test.ts
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-306
Nacro want to know what types of ID applicants have regardless of whether they are using personal savings or benefits to pay for their place, so we are updating the funding source page to always send them on to the ID page.
confirm:
=> CBA-306: show standard id page regardless of payment method selected on funding cas 2 page

server/form-pages/apply/bail-information/bail-hearing-information/bailHearingDate.test.ts, server/form-pages/apply/bail-information/bail-hearing-information/bailHearingDate.ts
On some of our pages with dates, the error validation is having the unintended side effect of generating an ISO string on the page body. We don’t have any validation on the bail hearing date page, so that’s not happening here. This is something we will need to revisit, but for now, we return the formatted date from the response method if there are valid date parts in the body, or else we return an empty string.
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-445
confirm:
=> Ensure bail hearing date is returned from page response

.github/workflows/pipeline.yml
Enabling prod deployments
Cloud platform config PR - https://github.com/ministryofjustice/cloud-platform-environments/pull/31494
System client request - https://dsdmoj.atlassian.net/browse/HAAR-3848
MFA request - https://mojdt.slack.com/archives/C02S71KUBED/p1744022395777419
We can use `kubectl -n hmpps-community-accommodation-prod get events` to debug if required, and if successfully deployed @adamhughes86 has prod access to login and smoke test
=> Enable prod deployment pipeline

helm_deploy/values-development.yaml
To make our environment variables consistent with the other CAS projects we are changing the dev environment name to lowercase
Once this has deployed @adamhughes86 will test and fire an event to sentry
=> Update dev environment name value to lowercase

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-test.yaml, server/middleware/setUpSentry.ts, server/utils/nunjucksSetup.ts
To have consistency with the wider CAS team we're renaming the environment variables
@adamhughes86 will test in the environments once deployed, create a new Sentry project to clear old environments, and then push test events to sentry
=> Updating environment variables

server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.test.ts, server/form-pages/apply/check-your-answers/check-your-answers/checkYourAnswers.ts, server/views/applications/show.njk, server/views/assess/applications/show.njk, server/views/components/applicationSummary/macro.njk
1. https://dsdmoj.atlassian.net/browse/CBA-455
2. https://dsdmoj.atlassian.net/browse/CBA-457
3. https://dsdmoj.atlassian.net/browse/CBA-454
Switches CRN/Prison number on what the app origin is
confirm:
=> feat: show crn/noms number dependant on app origin

e2e-tests/steps/assess.ts, server/views/partials/applicantDetails.njk
A recent accessibility fix to heading structure was causing this test to fail, because ‘Applicant details’ was no longer the first h2 element. I’ve replaced that with a test id locator to make the test more resilient.
confirm:
=> Fix E2E test

integration_tests/pages/apply/risks-and-needs/risk-information/acctPage.ts, server/form-pages/apply/risks-and-needs/risk-information/acct.test.ts, server/form-pages/apply/risks-and-needs/risk-information/acct.ts, server/views/applications/pages/risk-information/_risk-information-screen.njk, server/views/applications/pages/risk-information/acct.njk
https://dsdmoj.atlassian.net/browse/CBA-368
Add a line of content to page explaining that user can click through if no ACCT done. This would be using a small content change to avoid having to build a new yes/no screen for the ACCT pages. 
confirm:
=> feat: update text on ACCT page

server/utils/applications/getApplicationData.test.ts, server/utils/applications/getApplicationData.ts, server/utils/applications/managementInfoFromAppData.test.ts, server/utils/applications/managementInfoFromAppData.ts
Ensures bail hearing date is added to application as a primary field on submission.
confirm:
=> Fix - write bail hearing date as primary field on application

server/form-pages/apply/offence-information/previous-unspent-convictions/unspentConvictions.test.ts, server/form-pages/apply/offence-information/previous-unspent-convictions/unspentConvictions.ts
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-541?atlOrigin=eyJpIjoiZTNkMjg1ZGNiMDE1NGFmZDljOGRlNWMxZmE0MzIwOTYiLCJwIjoiaiJ9)
This fixes a bug when the safeguarding answer is "don't know", but instead displayed "No" when displaying the safeguarding answer.
confirm:
=> [CBA-541] Ensure correct safeguarding answer is displayed

server/form-pages/utils/questions.ts
https://dsdmoj.atlassian.net/browse/CBA-233
Two of the questions around bail hearing details do not have validation because court users may not know the answers to them. This means they are not mandatory and should be marked as optional, so we need to add (optional) in lowercase to the end of the questions. 
confirm:
=> fix: adds optional to bail hearing pages

server/form-pages/apply/offence-information/alleged-offences/custom-forms/allegedOffenceData.test.ts, server/form-pages/apply/offence-information/alleged-offences/custom-forms/allegedOffenceData.ts
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-504?atlOrigin=eyJpIjoiMDY3Y2MyZmRlZGYwNDMzZGIzZDA0MGE0ZjdhZTFmNjUiLCJwIjoiaiJ9)
When a page is the first in a task, the previous value should be 'taskList' so that the back button works as it's supposed to.
This change fixes a bug that could potentially trap a referrer when opening the alleged offences task for the first time.
confirm:
=> Fix previous page key for alleged offences data

server/form-pages/apply/offence-information/previous-unspent-convictions/custom-forms/unspentConvictionsData.test.ts, server/form-pages/apply/offence-information/previous-unspent-convictions/custom-forms/unspentConvictionsData.ts
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-531?atlOrigin=eyJpIjoiZjU2MTRlMjY0YmUxNDhkYmFiMGE5NzI5MWI0OTAyNTAiLCJwIjoiaiJ9)
The previous method currently refers to itself, this change points it to
the previous page.
confirm:
=> Fix previous page key for unspent convictions data

.github/workflows/pipeline.yml
[JIRA](https://dsdmoj.atlassian.net/browse/CBA-551?atlOrigin=eyJpIjoiZmM4ZDY5ZmE0YjlhNDQxODkxMzgwMDk0MGVkMjYwZTAiLCJwIjoiaiJ9)
Previously this was non-blocking as CAS2 Bail hadn't launched into private beta. As this is now live code, these tests will be required to pass before deploying to preprod, bringing it in line with the other UIs.
confirm:
=> Require e2e tests to pass for preprod deployment

integration_tests/fixtures/applicationData.json, server/form-pages/apply/risks-and-needs/health-needs/informationSources.test.ts, server/form-pages/apply/risks-and-needs/health-needs/informationSources.ts, server/form-pages/apply/risks-and-needs/risk-information/informationSources.test.ts, server/form-pages/apply/risks-and-needs/risk-information/informationSources.ts
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-367
- adds a response method to the information sources page to ensure user friendly rendering of data on the check your answers page
confirm:
=> CBA-367 - information sources - fix CYA view

server/form-pages/apply/bail-information/bail-hearing-information/bailHearingInformation.test.ts, server/form-pages/apply/bail-information/bail-hearing-information/bailHearingInformation.ts
We have decided to retain the court name and hearing medium because we believe it may be possible that this data is known even if the date is not.
confirm:
=> Retain data on save for bail hearing information page

integration_tests/pages/reports/managementInfoDownloadsPage.ts, integration_tests/tests/reports/download_management_info.cy.ts, server/controllers/report/reportsController.test.ts, server/controllers/report/reportsController.ts, server/paths/report.ts, server/routes/report.ts, server/views/reports/unauthorised.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-505
Adds a new role check to prevent users without the role "CAS2_MI" from viewing the reports page.
confirm:
=> Cba 505 users with cas 2 assessor role can view reports

package-lock.json, package.json
The latest version of Pact updates the version of Axios it depends on. Since we have had previous security alerts relating to the existing version of Axios, we should update Pact.
confirm:
=> Update @pact-foundation/pact to v15.0.1

server/data/applicationClient.test.ts, server/testutils/describeClient.ts, server/testutils/jest.setup.ts
This will cause open PRs to fail when an update to the API schema is detected, ensuring incompatible code isn't merged before the schema update.
confirm:
=> Enable openAPI test

e2e-tests/pages/basePage.ts, e2e-tests/steps/areaAndFundingSection.ts, server/views/applications/pages/area-information/gang-affiliations.njk
This was merged for testing purposes and can now be rolled back.
Reverts ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui#343
=> Revert "Add context to conditional radios on the gang affiliation page"

integration_tests/pages/apply/check_your_answers/check-your-answers/checkYourAnswersPage.ts, server/form-pages/apply/health-needs/health-needs/brainInjury.test.ts, server/form-pages/apply/health-needs/health-needs/brainInjury.ts, server/form-pages/apply/health-needs/health-needs/communicationAndLanguageRelevanceCheck.test.ts, server/form-pages/apply/health-needs/health-needs/communicationAndLanguageRelevanceCheck.ts, server/utils/checkYourAnswersUtils.ts
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-686
During manual testing we noticed that for the relevance check pages, there is a possibility that the cover page and the details page will be presented separately on the check your answers page, which may confuse referrers and assessors. 
To ensure that they will be presented together, we return answers for both pages (if applicable) from the cover page via a response method, and explicitly 'ignore' the details page when generating the check your answers page.
confirm:
Once we've merged it will be auto-deployed to the dev …
=> CBA-686 decide approach to relevance checks that links first and secondary pages

server/form-pages/apply/area-and-funding/funding-information/applicantID.ts
When we made the changes to the confirm consent page, we moved the page.next() call in the pagesController update method above the applicationService.save() method: https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-bail-ui/blob/bf8a917c9f2ffe61cac1d528b08b692f42ecc24c/server/controllers/apply/applications/pagesController.ts#L55.
We did this so that on the consent page we could work out the next page before removing the page data if the referrer answers no. However, in the case of the applicant ID page, page.next() relies on page.body.idDocuments being defined, which it will not be if no answer has been selected. And yet page.next() will be called before page.errors(), which is called inside applicationService.save().
This check will solve that problem, and is the …
=> Check if ID documents field is defined before chaining includes method

integration_tests/fixtures/applicationData.json, integration_tests/pages/apply/offences-and-concerns/previous-unspent-convictions/unspentConvictionsDataPage.ts, integration_tests/pages/apply/offences-and-concerns/previous-unspent-convictions/unspentConvictionsPage.ts, server/form-pages/apply/offences-and-concerns/previous-unspent-convictions/custom-forms/unspentConvictionsData.test.ts, server/form-pages/apply/offences-and-concerns/previous-unspent-convictions/custom-forms/unspentConvictionsData.ts, server/form-pages/apply/offences-and-concerns/previous-unspent-convictions/unspentConvictions.test.ts, server/form-pages/apply/offences-and-concerns/previous-unspent-convictions/unspentConvictions.ts, server/form-pages/utils/questions.ts, server/utils/applicationUtils.test.ts, server/utils/applicationUtils.ts, server/utils/formUtils.test.ts, server/utils/formUtils.ts, server/utils/nunjucksSetup.ts, server/views/applications/pages/previous-unspent-convictions/unspent-convictions-data.njk, server/views/applications/pages/previous-unspent-convictions/unspent-convictions.njk, server/views/partials/unspentConvictionsGuidanceDetails.njk
Jira ticket: https://dsdmoj.atlassian.net/browse/CBA-688
- adds new guidance to the unspent convictions 'data' page
- updates the questions on this page
- makes changes to the unspent convictions page to render the new data fields
Unspent convictions 'data' page
Unspent convictions page
Check your answers
Unspent convictions 'data' page
Unspent convictions page
Check your answers
confirm:
=> CBA-688: make changes to second previous convictions page

server/form-pages/apply/health-needs/health-needs/informationSources.ts, server/form-pages/apply/offences-and-concerns/risk-information/informationSources.ts
We added this guard when we moved from a single OASys information source to two separate ones, in case any in progress applications had selected that option. The guard ensures that that OASys option would render in CYA and the submitted applications views.
It has been two weeks since we implemented that change and it is now unlikely that any genuinely in progress applications are using that option, so we can remove the guard.
confirm:
=> Remove OASys information source guard

integration_tests/pages/apply/applicationListPage.ts, integration_tests/pages/page.ts, integration_tests/tests/apply/dashboard.cy.ts, integration_tests/tests/apply/prison-bail-applications.cy.ts, server/controllers/apply/applicationsController.test.ts, server/controllers/apply/applicationsController.ts, server/views/applications/index.njk, server/views/applications/overview.njk, server/views/applications/prison-applications.njk
Jira: https://dsdmoj.atlassian.net/browse/CBA-726
- adds sub navigation for prison bail referrers to navigate between the prison bail dashboard and their applications dashboard (for now this is behind a feature flag)
- adds integration tests for applications dashboard
confirm:
=> CBA-726 add sub navigation to applications dashboards
